### ISSUE TITLE
一直在重连

### ISSUE THREAD

**Issue by powerttt** [zimv/websocket-heartbeat-js#11]
一直尝试重连，而导致断开连接。
`connect success
index.vue?6ced:126 close connecti...
index.vue?6ced:129 reconnecting...
index.vue?6ced:132 connect success
index.vue?6ced:126 close connecti...
index.vue?6ced:129 reconnecting...
index.vue?6ced:132 connect success
index.vue?6ced:126 close connecti...
index.vue?6ced:129 reconnecting...
index.vue?6ced:132 connect success
`

**Comment by zimv** [comment]
仔细看看代码，之前也有这样的issues 后面他们都各自发现了自己的问题了。

**Comment by tryhardest** [comment]
^
Take a closer look at the code. There were such issues before, and they each found their own problems.
