### ISSUE TITLE
大佬你这个封装好的webscoket我一个页面会运行多个实例。这个没问题吧？

### ISSUE THREAD

**Issue by storagess** [zimv/websocket-heartbeat-js#17]
同时建立多个webscoket连接，用工厂模式会产生闭包。用数组就不会。大佬你知道还有什么好的办法吗

**Comment by zimv** [comment]
你标题的问题是，我这个能不能运行多个实例，是可以的，new多个实例就行了。
同时建立多个ws，会产生闭包，闭包有什么问题吗？
