### ISSUE TITLE
作者你好，我这有个问题。

### ISSUE THREAD

**Issue by storagess** [zimv/websocket-heartbeat-js#18]
这个重连，我需要根据状态来判断是否需要重连。有暴露手动进行重连的函数吗。比如用户离线，我需要断开。然后用户又上线来我需要对之前断开的webscoket进行重连

**Comment by zimv** [comment]
用户下线直接手动close把socket关闭了，重新上线还是通过new新建实例。重连是一种保障链接的机制，并不是你上面那种用法

**Comment by storagess** [comment]
但是我这会维护多个new.一个账号一个New

**Comment by storagess** [comment]
用户随时可以退出和登录

**Comment by zimv** [comment]
重连和新建一个实例，在代码底层，其实都是new一个原生的websocket，所以你不用纠结重连。需要建立链接的时候传入url和参数重新new一个就可以了，需要关闭就把之前建立的close掉就行了

**Comment by storagess** [comment]
我得保存之前的，目前是放在数组里面。因为用户登录成功在线我就建立。离线我就关闭并删除new的

**Comment by zimv** [comment]
你说的像是后端逻辑？你说的数组 是后端？

**Comment by storagess** [comment]
不是。是这样的一个情景，我有一个账号。他登录上后。我就要建立连接。然后又有一个。每次登录都需要建立链接。然后还会下线。上线，都要从新进行断开和连接

**Comment by zimv** [comment]
你可以看看源码是如何重连的。这个库的重连是针对心跳的，保障稳定的，当一个socket异常断开后，实例自动重连，是为了不让业务代码去管理稳定性的问题，属于技术抽象。
你所说的重连，实际是业务中的建立和断开连接，属于业务代码，这个库不解决业务代码的问题，因为通用性上做这个是不合适的。你现在就是应该在上线时new一个socket，下线时close掉。下次再上线，又重新new一个socket。

**Comment by storagess** [comment]
嗯嗯。我用其他方法。因为NEW都保存在 数组里进行维护的。
