### ISSUE TITLE
博主你好，我想问下你这个连接操作

### ISSUE THREAD

**Issue by storagess** [zimv/websocket-heartbeat-js#20]
这个我设置了  pingTimeout: 1000,
        repeatLimit: 1  这个为什么会一直进行重连？ 我设置来重连次数是1。可是这个会一直给ws发送消息。然后创建一个新链接

**Comment by zimv** [comment]
能看下你代码吗，发出来

**Comment by storagess** [comment]
this.webscokeArr[0] = new this.WebsocketHeartbeatJs({
        url: this.$configurationGlobal.webSocket + "ws?www=" + data.www,
        pingTimeout: 1000,
        repeatLimit: 1
      });

**Comment by zimv** [comment]
这个重连次数限制主要是针对断开链接以后，尝试重新链接ws的次数。你说的ws发送消息，那个是心跳消息，需要后端回复一个心跳回执，要不前端以为后端没有响应就会重新请求。如果limit你不设置，就会一直尝试请求，直到请求成功

**Comment by storagess** [comment]
@zimv   我设置了

**Comment by zimv** [comment]
有网页地址吗 我看看

**Comment by storagess** [comment]
this.webscokeArr[0] = new this.WebsocketHeartbeatJs({
    url: this.$configurationGlobal.webSocket + "ws?www=" + data.www,
    pingTimeout: 1000,
    repeatLimit: 1
  });
不是设置了     repeatLimit: 1

**Comment by storagess** [comment]
后端并没有给我心跳回执。

**Comment by storagess** [comment]
@zimv 后端没有给我心跳回执。我这边会一直进行Ping消息.然后一直会新建一个ws链接

**Comment by zimv** [comment]
后端必须返回心跳响应消息 ，否则前端 以为后端出问题了，就会主动去重新连接。
文档有专门说明：
2.ping & pong

前端发送ping消息，后端收到后，需要立刻返回pong消息，pong消息可以是任何值，websocket-heartbeat-js并不处理pong消息，而只是在收到任何消息后，重置心跳，因为收到任何消息就说明连接是正常的。

**Comment by storagess** [comment]
重置心跳 @zimv  重置心跳是什么意思

**Comment by zimv** [comment]
你要不先仔细看下文档，理解下原理。https://github.com/zimv/websocket-heartbeat-js/blob/master/README-zh.md

**Comment by storagess** [comment]
@zimv  这个估计不行。我做的是聊天系统。只要别人给我发送消息。这个不就代表收到任何消息了吗。别人不给我发送消息不就代表挂了。需要重连。

**Comment by zimv** [comment]
聊天系统还是走的服务端中转发送的消息。客户端发送消息，服务端接收再转发给另一个客户端。你让服务端回应一下你的心跳消息不就行了

**Comment by storagess** [comment]
是的，我需要让他规定一个类型。专门是处理心跳的类型。我大致明白。我这边规定一个时间。每隔多少去发送ping。后端接受ping 给我返回。然后保持正常连接。如果我ping之后。后端并没有给我响应。代表挂了。我去重连。然后限制重连次数

**Comment by zimv** [comment]
不用限制重连次数，因为你一定希望一直保持连接。重连次数意思是如果重连一次，没有连上就不尝试了。但是业务应该是需要一直去尝试直到连接成功的

**Comment by storagess** [comment]
我们这边后端。说什么重连死循环了。。因为每次重连都需要从新开一个连接。之前的连接有做关闭了处理吗

**Comment by zimv** [comment]
是因为他们不返回消息，所以重连的，重连心跳本身就是一个循环。如果返回了消息就不会重连了，还有pingmsg时间1秒太短了，10秒+左右请求一次，就行

**Comment by storagess** [comment]
也就是说我隔15秒一次。收到后端给我发的消息值

**Comment by storagess** [comment]
这样循环检测

**Comment by zimv** [comment]
嗯 多少时间内没收到任何消息 就会去检测一下，后端返回了 就说明 连接正常

**Comment by storagess** [comment]
但是这里还有个问题。这里如果后端隔了一段时间没有给我返回消息。我需要断开连接。而不是进行重连

**Comment by zimv** [comment]
那就是limit 设置为0，就不会尝试重连

**Comment by storagess** [comment]
那这时候。有回掉监听吗

**Comment by storagess** [comment]
onclons

**Comment by storagess** [comment]
@zimv  无响应是不是代表关闭了？那我能检测到webscoke的关闭连接回调函数吧

**Comment by zimv** [comment]
是。onclose钩子函数。
