### ISSUE TITLE
protocal传参

### ISSUE THREAD

**Issue by lkdghzh** [zimv/websocket-heartbeat-js#21]
请问如何传入websocket constructor里的protocal参数？

**Comment by zimv** [comment]
能详细说说吗？没懂这个意思

**Comment by lkdghzh** [comment]
构造函数
WebSocket(url[, protocols])
返回一个 WebSocket 对象。里面protocols这个参数

**Comment by zimv** [comment]
实例化之后,会有个ws属性文档中有说明，ws就是原生的websocket实例，ws.protocol 就可以拿到协议。
`let websocketHeartbeatJs = new WebsocketHeartbeatJs({
    url: 'ws://xxxxxxx'
});
websocketHeartbeatJs.ws`

**Comment by JakeWoki** [comment]
WebsocketHeartbeatJs的pingMsg使用string无法传protocal，[websocket-heartbeat-miniprogram](https://github.com/zimv/websocket-heartbeat-miniprogram)是js写的没有限制可以用

**Comment by zimv** [comment]
@JakeWoki 我现在把WebSocket构造函数的protocols参数定义了，然后把d.ts文件的pingMsg类型设置为any，这样应该可以支持你的需求了吧？

**Comment by JakeWoki** [comment]
可以的  多谢

**Comment by zimv** [comment]
@JakeWoki 1.1.0版本发布了 试下呢

**Comment by JakeWoki** [comment]
可以了
