### ISSUE TITLE
[Feature] Will add a filter abuot Pong messages for “onmessage” function

### ISSUE THREAD

**Issue by YuaXan** [zimv/websocket-heartbeat-js#26]
That isn’t usually need messages of Pong that most people .
对于多数人来说，不需要pong消息

So, I hope  `@zimv` to add a filter for `onmessage`.
所以希望作者大大为`onmessage`加入一个过滤

We can setting a `pongMsg`, like `pingMsg` too, and to filter `pongMsg`.
我们可以像`pingMsg`一样设置`pongMsg`, 之后过滤 `pongMsg`

This is my idea.

https://github.com/zimv/websocket-heartbeat-js/blob/dad676c04a5e7a2866437da8f77c7e0ea7137b84/lib/index.js#L68
```javascript
this.ws.onmessage = (event) => {
  if (event.data !== this.opts.pongMsg) {
    this.onmessage(event);
  }
  this.heartCheck();
};
```

**Comment by zimv** [comment]
对于所有收到的消息，前端都应该在onmessage中写好预期的处理逻辑，如果不是预期的响应消息，前端业务逻辑就应该忽略，而并不是库本身去做这额外的过滤，意义不大。不仅仅是pongMsg不需要处理，后端可能会发送一些根本无用的消息，而我们的业务逻辑就是处理预期的消息，忽略非预期的消息。
比如，下面的业务逻辑只需要处理接受的expect消息，而其他的pongMsg或者123或者任何其他消息，前端都是忽略的
`
websocketHeartbeatJs.onmessage = (e) => {
    if(e.data === 'expect') console.log('is expect');
}
`

**Comment by YuaXan** [comment]
> 对于所有收到的消息，前端都应该在onmessage中写好预期的处理逻辑，如果不是预期的响应消息，前端业务逻辑就应该忽略，而并不是库本身去做这额外的过滤，意义不大。不仅仅是pongMsg不需要处理，后端可能会发送一些根本无用的消息，而我们的业务逻辑就是处理预期的消息，忽略非预期的消息。
> 比如，下面的业务逻辑只需要处理接受的expect消息，而其他的pongMsg或者123或者任何其他消息，前端都是忽略的
> `websocketHeartbeatJs.onmessage = (e) => { if(e.data === 'expect') console.log('is expect'); }`

但是我觉得每次要写一次过滤也挺麻烦的，可以增加这个功能也是可有可无的

**Comment by zimv** [comment]
> > 对于所有收到的消息，前端都应该在onmessage中写好预期的处理逻辑，如果不是预期的响应消息，前端业务逻辑就应该忽略，而并不是库本身去做这额外的过滤，意义不大。不仅仅是pongMsg不需要处理，后端可能会发送一些根本无用的消息，而我们的业务逻辑就是处理预期的消息，忽略非预期的消息。
> > 比如，下面的业务逻辑只需要处理接受的expect消息，而其他的pongMsg或者123或者任何其他消息，前端都是忽略的
> > `websocketHeartbeatJs.onmessage = (e) => { if(e.data === 'expect') console.log('is expect'); }`
> 
> 但是我觉得每次要写一次过滤也挺麻烦的，可以增加这个功能也是可有可无的

上面的意思应该是不用过滤吧。就是onmessage中，理论上都应该只判断需要的数据，如果是需要的数据才走后续流程。逻辑上是主动接收需要的数据，而不是主动过滤不需要的数据

**Comment by zimv** [comment]
如果真的有人要用pongMsg 来做什么其他事情的话，那就有点坑了。这个点 还是更偏向业务逻辑，非通用逻辑，就不考虑加到库里了。谢谢你的issue
