### ISSUE TITLE
Throws error when bundled in code that also runs on node.js

### ISSUE THREAD

**Issue by ResourcefulNetwork** [zimv/websocket-heartbeat-js#29]
I'm running the same code on client side (browser) and server side (node.js)
I _will not_ be using this library on the server side, but it needs to load properly.

Right now when the code executes I get this error `window is not defined`

**Comment by ResourcefulNetwork** [comment]
the error comes from this code in `dist/index.js` : `(window,function(){return ...`

```
 window is not defined
    at Object.<anonymous> (C:\web\dacore\dacore.org\node_modules\websocket-heartbeat-js\dist\index.js:1:224)
    ```

**Comment by ResourcefulNetwork** [comment]
If I change dist/index.js manually to this I get no error:
```
(typeof(window) !== 'undefined' ? window : null,function(){return ...
```

**Comment by zimv** [comment]
The bug was fixed in version 1.0.11. You need to update the new version.

**Comment by zimv** [comment]
You are right! I will fix it in no time.

**Comment by zimv** [comment]
Now, you can try it in the new version 1.0.13. Thanks for your issue.

**Comment by ResourcefulNetwork** [comment]
great, its working now. Thank you for the quick fix!
