### ISSUE TITLE
源码的一个疑问

### ISSUE THREAD

**Issue by wjkang** [zimv/websocket-heartbeat-js#3]
```js
this.pongTimeoutId = setTimeout(() => {
            //如果onclose会执行reconnect，我们执行ws.close()就行了.如果直接执行reconnect 会触发onclose导致重连两次
            this.ws.close();
}, this.opts.pongTimeout);
```
为什么直接执行reconnect 会触发onclose导致重连两次

**Comment by zimv** [comment]
因为reconnect会调用createWebSocket创建一个新的websocket对象，新对象会去建立连接，而此时旧的对象被释放的时候，onclose被触发，就会调用旧对象的reconnect再去创建一个新websocket对象，这样就调用两次了。所以这里直接把旧对象close了，旧对象的onclose被触发，便会去创建新websocket对象

**Comment by zimv** [comment]
如果你觉得没问题了，就回复一下，我关了这个issue

**Comment by wjkang** [comment]
OK
