### ISSUE TITLE
重连的问题

### ISSUE THREAD

**Issue by lemures-t** [zimv/websocket-heartbeat-js#4]
```javascript
WebsocketHeartbeatJs.prototype.createWebSocket = function(){
    try {
        this.ws = new WebSocket(this.opts.url);
        this.initEventHandle();
    } catch (e) {
        this.reconnect();
        throw e;
    }     
};

WebsocketHeartbeatJs.prototype.reconnect = function(){
    if(this.lockReconnect || this.forbidReconnect) return;
    this.lockReconnect = true;
    this.onreconnect();
    //没连接上会一直重连，设置延迟避免请求过多
    setTimeout(() => {
        this.createWebSocket();
        this.lockReconnect = false;
    }, this.opts.reconnectTimeout);
};
```
```this.lockReconnect = false``` 是不是应该放在 ```this.createWebSocket()``` 前面？

createWebSocket 报错后，运行 reconnect 方法，this.lockReconnect 是 undefined，this.lockReconnect 被置为 true, 注册一个 setTimeout 方法，reconnectTimeout 后，执行该方法，运行 this.createWebSocket() ，再报错，再运行 reconnect 方法，this.lockReconnect 此时为 true，直接 return。不会再运行 createWebSocket 方法进行重连。

是不是需要在 setTimeout 方法里 this.createWebSocket 前，就把 this.lockReconnect 置为 false ？

**Comment by zimv** [comment]
其实这里写在前面或者后面都一样的，在initEventHandle里绑定了onerror。浏览器创建ws实例的时候，是异步去请求的，同步的代码会被先执行。发现地址错误之后，会触发onerror。try catch只是兼容一些其他错误。
最后，还是非常感谢你！

**Comment by zimv** [comment]
this.ws = new WebSocket(this.opts.url);。new之后，会立刻返回实例给this.ws，至于链接错误什么的，this.ws.onerror通过触发得知。这时同步的代码已经被执行了
