### ISSUE TITLE
能不能实现单例连接呢？

### ISSUE THREAD

**Issue by kgloveyou** [zimv/websocket-heartbeat-js#41]
在options参数相同的情况下，如何创建一个单例的ws对象呢？而不是每new一个，就新建一个ws连接。

**Comment by zimv** [comment]
@kgloveyou 继续讨论呀，我在听

**Comment by kgloveyou** [comment]
@zimv ，目前接手的离职同事的代码如下
```
        ws.current = new WebsocketHeartbeatJs({
          url: url || uri,
          pingMsg: 'ping'
        });
```
这样每调用一次，就是在浏览器新建一个websocket长连接，后台需要同一个URL共用一个连接，而不是每次都new新的连接出来。这种情况该如何实现呢？

**Comment by zimv** [comment]
如果是全局单例的话 这里不应该用hooks的方式，就用一个单独的变量来存储WebsocketHeartbeatJs的实例，然后全局可以调用

**Comment by paulussimanjuntak** [comment]
Hi, I want to ask, how do I make the onreconnect function use the new token in the url

for example
`    let options = {
        url: `ws://192.168.18.3:8081/homes?jwt=123`,
        pingMsg: "ping",
        pingTimeout: 3000,
      };
    let websocketHeartbeatJs = new WebsocketHeartbeatJs(options);

    websocketHeartbeatJs.onreconnect = () => {
      options = {
        url: `ws://192.168.18.3:8081/homes?jwt=321`,
        pingMsg: "ping",
        pingTimeout: 3000,
      };
      console.log("reconnecting...", options);
      websocketHeartbeatJs = new WebsocketHeartbeatJs(options);
    };

`
