### ISSUE TITLE
repeatLimit设置次数为0, 依然会无限连接

### ISSUE THREAD

**Issue by YHoney7** [zimv/websocket-heartbeat-js#42]
在关闭的issues里看到这个问题, 但是没有找到解决方案
![image](https://user-images.githubusercontent.com/49771966/215303505-c940a94f-5e37-488a-a993-87d53b30610d.png)
![image](https://user-images.githubusercontent.com/49771966/215303525-0fd46c9e-3115-4d7f-97e6-f937cb5d980a.png)

**Comment by zimv** [comment]
我改下，马上发个版本。之前这个参数的逻辑 需要>1

**Comment by zimv** [comment]
我改下，马上发个版本。之前这个参数的逻辑 需要>1

**Comment by zimv** [comment]
我改下，马上发个版本。之前这个参数的逻辑 需要>1

**Comment by YHoney7** [comment]
@zimv 好的大佬, 非常感谢, 今天就能发布新版本吗

**Comment by zimv** [comment]
1.1.1已经发布 你试试

**Comment by YHoney7** [comment]
ok了, 测试没有问题, 点个star
