### ISSUE TITLE
pingMsg能否支持函数？

### ISSUE THREAD

**Issue by gaaoge** [zimv/websocket-heartbeat-js#44]
后端有需求心跳信息每次需要传不同的id，能否把pingMsg调整为支持函数的形式，代码类似如下：

`this.ws.send(typeof this.opts.pingMsg === 'function' ? this.opts.pingMsg(): this.opts.pingMsg);`

**Comment by zimv** [comment]
@gaaoge 可以的，我看今天能不能更新一版本

**Comment by gaaoge** [comment]
@zimv 没问题了👍🏻
