### ISSUE TITLE
vue3+ts环境 , 使用demo里的代码钩子函数不执行

### ISSUE THREAD

**Issue by cnsimplo** [zimv/websocket-heartbeat-js#45]
见下图.
注释的代码可以 , 下面的无法执行.  ?
![image](https://github.com/zimv/websocket-heartbeat-js/assets/23493320/7816327c-f2d0-4c8f-9083-9aa71b36e316)

**Comment by zimv** [comment]
> 见下图. 注释的代码可以 , 下面的无法执行. ? ![image](https://user-images.githubusercontent.com/23493320/269477101-7816327c-f2d0-4c8f-9083-9aa71b36e316.png)

连上了才会触发onopen，你这里报错没有，你把onerror close这些勾子都加上看看
