### ISSUE TITLE
WebSocket 应用逻辑

### ISSUE THREAD

**Issue by xialvjun** [zimv/websocket-heartbeat-js#6]
根据我的实际测试, 发现:
```md
server 与 client 对 websocket 处理逻辑完全相同:
一端正常关闭，另一端也会正常关闭。
一端异常关闭（断网，更准确的说是找不到此 ip, 再准确的说是找不到此电脑），另一端会等待一段时间后再关闭。
如果这段时间内找到了此 ip:
   如果双方进程都保留着 websocket 连接，则连接恢复正常，并且把这段时间内 send 的消息一块发完(只保证自己这边的顺序，至于双方的顺序就不被保证了)
   如果其中一方连接丢失，则另一方会在 send 的时候发现并立即触发自己的 close。
       或者不 send 消息, 只是等待一段时间后关闭自己
连接正常的时候，哪怕没有任何消息，也不会关闭：所以本质上来说，websocket 本身就有个底层传输层心跳包，不然无法出现“等待一段时间后再关闭”的情况
                     但长时间没有消息，运营商可能会断开连接，让两端各自认为另一端异常关闭，并且一直找不到 ip，哪怕明明 ip 在那儿，连接在那儿, send 消息也只会 buffer 起来.
```

于是, 单纯的对于使用而言, 只要这样就好:
```js
client.onclose = () => {
  setState({closed:true}); // 改变 UI
  client.reconnect();
}
```
如果要求界面上完全显示（即要不 client 显示自己已断开连接，要不 client 就要立即响应 server 变化）, 那 server 要每秒向 client 发 **应用层心跳**, client 如果两秒内没收到心跳，就断开自己，并显示已断开，并重新连接
如果要求 server 消息不丢失（事实上做不到, 或者说非常复杂，应该改变程序逻辑模型）

# 所以, 心跳只需要服务端发心跳, 客户端检测心跳决定是否断开重连

其实, 当 websocket 连接断开的时候, 不是什么 前端 后端 无感知, 而是它们都有 buffer, 它们本身就有传输层心跳, 它们立即就感知到断网了, 但是它们在等待着重新联网, 期间发消息都发到 buffer 上.

**Comment by zimv** [comment]
对，我之前在一些协议层面的理解和实现方面理解有误，后面得改改文章。
要保证数据不丢失的话，可以做消息回执，也就是a给b发送消息id=1，b返回收到id=1的消息，如果没有回执a可以再次发送消息id=1。
大部分时候在应用交互过程中比我们想象中的复杂，我当时做心跳的时候在16年，那时候在测试的时候对于不同浏览器，包括应用测试过程中，就是出现了一些不稳定的因素，因此引入了心跳重连机制。
因为ws链接必须是前端主动请求，因此重连肯定是给前端来做，也如你所说让服务端发送心跳，前端来接收，这样会多节约一点带宽，因为如果是前端发送心跳，后端需要返回心跳，也就是ping pong的过程会有两次数据传递。而后端来发送心跳的话，就只需要发送ping，前端不需要回应。但是这样造成了一个问题。前端需要和后端约定好心跳间隔，比如后端设置10秒发送一次请求，那前端就需要设置一个安全值，比如12秒内没收到就重连。这样的问题在于调节时间就变得不那么灵活了，需要双方都同时确定一个时间约定。
而如果前端来发送ping 后端返回pong的话，那么间隔时间就只需要前端自己控制了。加上我的代码把收到的任何后端信息都可以当作是链接正常，从而重置心跳时间，这样也节约了一些重复请求。
使用我这样的方式，后端比较轻松，只需要在onmessage写一段代码
`if(msg=='heartbeat') socket.send(anything);`

**Comment by xialvjun** [comment]
嗯, 的确, 其实只要把这个逻辑讲清楚了, 大家就都知道该怎么做最适合自己了. 这个 issue 关了.

**Comment by zimv** [comment]
当时我在写文章的时候 都看的是表象，没有把一些原理述说清楚，文章其实也稍微改过几次，有些不稳定性，当时在测试的时候，也没找到重现的方式，惭愧惭愧

**Comment by xialvjun** [comment]
其实很好了, 能写文章的比我这种懒得写文章的要强多了.
好了, 你别回了. 再客气要客气个没完了.
