### ISSUE TITLE
我想重联时给url增加参数如何实现

### ISSUE THREAD

**Issue by owen-gxz** [zimv/websocket-heartbeat-js#7]
我这边后台想知道用户是不是第一次连接。。向修改url可以实现吗？

**Comment by zimv** [comment]
请求里可以加参数

**Comment by zimv** [comment]
或者链接成功后 马上推送一条消息

**Comment by owen-gxz** [comment]
请求里面设置好URL之后是没法在修改了。。
连接成功我就会接收到后台历史消息，我想如果重联的时候不给我推送历史消息，所以需要修改某些值，，但如果实在不行。我这边会在重联那个方法里面，设置一个cookie，后台查询这个cookie来判断是不是重联

**Comment by zimv** [comment]
这种情况 你在前端加个flag，如果已经接收过历史消息 就不执行相关逻辑就行了

**Comment by zimv** [comment]
其实拉不拉历史消息，应该前端发一个消息，发送后才返回历史消息，而不是一链接上就返回

**Comment by owen-gxz** [comment]
这是我第二种方式

**Comment by zimv** [comment]
如果要修改url可以这样
let ws = new WebsocketHeartbeatJs();
ws.opts.url = 'xxx'

**Comment by zimv** [comment]
你可以在重连方法里写 ws.opts.url = 'xxx' 来重写url
